.\" Copyright (c) 2023 Alex Arx <aa@manpager.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd November 16, 2024
.Dt GPM 1
.Os
.Sh NAME
.Nm gpm
.Nd general secret (or password) manager
.Sh SYNOPSIS
.Nm
.Op Fl d Ar dir
.Ar command
.Op Ar arg ...
.Sh DESCRIPTION
The utility
.Nm
is a secret manager.
Secrets are stored in a directory tree as files, encrypted with
.Xr gpg 1
or a custom command (see
.Sx ENVIRONMENT ) .
.Nm
provides several commands for manipulating secrets.
Commands may be specified by their shortest unique prefix (all characters
after are ignored).
Commands may accept additional arguments.
Commands may be preceeded by global options as follows:
.Bl -tag -width Ds
.It Fl d Ar dir
The directory to store and retrieve secrets from.
Overrides
.Ev GPM_DIR .
.El
.Pp
The
.Nm
commands are as follows:
.Bl -tag -width Ds
.It Xo
.Cm add
.Op Fl Nnm
.Ar name
.Xc
Create a new secret
.Ar name .
The new secret is read from stdin.
If used from a TTY without the
.Fl m
flag, a single line is read twice, and not echoed.
Otherwise, an arbitrary amount of lines is read normally once.
If
.Fl n
is specified without
.Fl N
chop off any last newline character of input.
.Pp
Options in the
.Ev GPM_ADD
environment variable are passed to
.Nm
.Cm add
automatically, before any options specified on the command line.
.It Xo
.Cm copy
.Op Fl Nn
.Op Fl d Ar delcmd
.Op Fl i Ar incmd
.Op Fl o Ar outcmd
.Op Fl s Ar time
.Ar name
.Xc
Copy the secret
.Ar name
by piping it to
.Ar incmd .
After
.Ar time
seconds, run
.Ar delcmd
if
.Ar outcmd
prints plaintext secret
.Ar name
on standard output.
Without
.Fl d , i , o
or
.Fl s ,
the values of
.Ev GPM_COPY_DELCMD , GPM_COPY_INCMD , GPM_COPY_OUTCMD
and
.Ev GPM_COPY_SLEEP
are used.
The default values are
.Ql xclip </dev/null ,
.Ql xclip ,
.Ql xclip -o
and 60.
If
.Ar time
is 0,
.Ar delcmd
is not run.
If
.Fl n
is specified without
.Fl N ,
chop off any last newline character before passing the secret to
.Ar incmd .
.Pp
Options in the
.Ev GPM_COPY
environment variable are passed to
.Nm
.Cm copy
automatically, before any options specified on the command line.
.It Cm ls
List existing secrets, using the command in
.Ev GPM_LSCMD
if set.
.Pp
Options in the
.Ev GPM_LS
environment variable are passed to
.Nm
.Cm ls
automatically, before any options specified on the command line.
.It Cm mv Ar from Ar to
Rename secret
.Ar from
to
.Ar to .
.Pp
Options in the
.Ev GPM_MV
environment variable are passed to
.Nm
.Cm mv
automatically, before any options specified on the command line.
.It Cm rm Ar name ...
Remove secrets specified on the command line.
.Nm
will ask for confirmation before each removal.
.Pp
Options in the
.Ev GPM_RM
environment variable are passed to
.Nm
.Cm rm
automatically, before any options specified on the command line.
.It Xo
.Cm show
.Op Fl Nn
.Ar name
.Xc
Decrypt the secret
.Ar name ,
and print plaintext to stdout.
If
.Fl n
is specified without
.Fl N ,
chop off any last newline character of output.
.Pp
Options in the
.Ev GPM_SHOW
environment variable are passed to
.Nm
.Cm show
automatically, before any options specified on the command line.
.El
.Sh ENVIRONMENT
.Bl -tag -width XDG_DATA_HOME
.It Ev GPM_ENCCMD
Command used for encryption.
.Dq gpg -e \-\-
if not set.
.It Ev GPM_DECCMD
Command used for decryption.
.Dq gpg -d \-\-
if not set.
.It Ev GPM_DIR
Directory in which the secrets are stored.
.It Ev XDG_DATA_HOME
If
.Ev XDG_DATA_HOME
is set, but
.Ev GPM_DIR
isn't, the default secret directory is
.Pa $XDG_DATA_HOME/gpm .
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa $HOME/.gpm
The default secret directory if neither
.Ev GPM_DIR ,
nor
.Ev XDG_DATA_HOME
are set.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Tab-completion may be set, e.g. with
.Xr ksh 1 :
.Bd -literal -offset indent
set -A complete_gpm_1 -- add copy ls mv rm show
set -A complete_gpm -- $(gpm ls)
.Ed
.Sh SEE ALSO
.Xr gpg 1 ,
.Xr gpg2 1 ,
.Xr pm 1 ,
.Xr xclip 1
.Sh AUTHORS
.An Alex Arx Aq Mt aa@manpager.org .
