#!/bin/sh

files=$(pm l | tr \\n ' ')
awk -vfiles="$files" -vstty="$(stty -g)" '
	BEGIN {
		system("stty -echo")
		printf("pass:")
		getline pass
		system("stty " stty)

		split(files, a)
		for (f in a)
			print pass
	}
' | for f in $files; do
	pm s "$f" | gpm "$@" add "$f"
done
