.\" Copyright (c) 2023-2025 Alex Arch <aa@manpager.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd February 15, 2025
.Dt SECSTORE 1
.Os
.Sh NAME
.Nm secstore
.Nd manage secure (or secret) storage
.Sh SYNOPSIS
.Nm
.Op Fl d Ar dir
.Ar command
.Op Ar arg ...
.Sh DESCRIPTION
The utility
.Nm
is a secret manager.
Secrets are stored in a directory tree as files, encrypted with
.Xr gpg 1
or a custom command (see
.Sx ENVIRONMENT ) .
.Nm
provides several commands for manipulating secrets.
Commands may accept additional arguments.
Commands may be preceeded by global options as follows:
.Bl -tag -width Ds
.It Fl d Ar dir
The directory to store and retrieve secrets from.
Overrides
.Ev GPM_DIR .
.El
.Pp
The
.Nm
commands are as follows:
.Pp
.Bl -tag -compact -width Ds
.It Xo
.Cm add
.Op Fl fm
.Ar name
.Xc
Create a new secret
.Ar name .
The new secret is read from stdin.
If used from a TTY without the
.Fl m
flag, a single line is read twice, and not echoed.
Otherwise, an arbitrary amount of lines is read once (and echoed).
Unless
.Fl f
is specified, overwriting existing secrets is not allowed.
.Pp
.It Xo
.Cm copy
.Op Fl d Ar delcmd
.Op Fl i Ar incmd
.Op Fl o Ar outcmd
.Op Fl s Ar time
.Ar name
.Xc
.Dl Pq alias: Cm cp
Copy the secret
.Ar name
by piping it to
.Ar incmd .
After
.Ar time
seconds, run
.Ar delcmd
if
.Ar outcmd
prints plaintext secret
.Ar name
on standard output.
Without
.Fl d , i , o
or
.Fl s ,
the values of
.Ev SECSTORE_COPY_DELCMD , SECSTORE_COPY_INCMD , SECSTORE_COPY_OUTCMD
and
.Ev SECSTORE_COPY_SLEEP
are used.
The default values are
.Ql xclip </dev/null ,
.Ql xclip ,
.Ql xclip -o
and 60.
If
.Ar time
is 0,
.Ar delcmd
is not run.
.Pp
.It Cm list
.Dl Pq alias: Cm ls
Produce a complete file listing for the secret storage.
.Pp
.It Xo
.Cm move
.Op Fl f
.Ar source
.Ar target
.Xc
.It Xo
.Cm move
.Op Fl f
.Ar source ...
.Ar directory
.Xc
.Dl Pq alias: Cm mv
Rename secret
.Ar source
to
.Ar target .
If more than two arguments are specified, or
.Ar target
ends with a slash
.Pq Ql / ,
moves the
.Ar source
secrets to
.Ar directory .
.Pp
.It Xo
.Cm remove
.Op Fl f
.Ar name ...
.Xc
.Dl Pq alias: Cm rm
Remove secrets specified on the command line.
.Nm
will ask for confirmation before each removal, unless
.Fl f
is specified.
.Pp
.It Cm print Ar name
Decrypt the secret
.Ar name ,
and print plaintext to stdout.
.El
.Sh ENVIRONMENT
.Bl -tag -width XDG_DATA_HOME
.It Ev SECSTORE_ENCCMD
Command used for encryption.
.Dq gpg -e \-\-
if not set.
.It Ev SECSTORE_DECCMD
Command used for decryption.
.Dq gpg -dq \-\-
if not set.
.It Ev SECSTORE_DIR
Directory in which the secrets are stored.
.It Ev XDG_DATA_HOME
If
.Ev XDG_DATA_HOME
is set, but
.Ev SECSTORE_DIR
isn't, the default secret directory is
.Pa $XDG_DATA_HOME/secstore .
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa $HOME/.secstore
The default secret directory if neither
.Ev SECSTORE_DIR ,
nor
.Ev XDG_DATA_HOME
is set.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Tab-completion may be set, e.g. with
.Xr ksh 1 :
.Bd -literal -offset indent
set -A complete_secstore_1 -- add copy list move remove print
set -A complete_secstore -- $(secstore list)
.Ed
.Sh SEE ALSO
.Xr gpass 1 ,
.Xr gpg 1 ,
.Xr gpg2 1 ,
.Xr xclip 1
.Sh AUTHORS
.An Alex Arch Aq Mt aa@manpager.org .
